// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFqVL29mV96nhFgfCSSZ_eVkcv63B2VoE',
    appId: '1:151675978284:android:df2f9a3f69cb8d179f8789',
    messagingSenderId: '151675978284',
    projectId: 'flutter-bloc-photo-library',
    storageBucket: 'flutter-bloc-photo-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLUC3Ixc1Z0XRdWU2jin5a1I4pFEy1B4',
    appId: '1:151675978284:ios:bcb042708c487a6e9f8789',
    messagingSenderId: '151675978284',
    projectId: 'flutter-bloc-photo-library',
    storageBucket: 'flutter-bloc-photo-library.appspot.com',
    iosClientId: '151675978284-7duav54iob484r4n7iianmo3vc7reb9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.imagePickerBlocApp',
  );
}
